[project]
name = "bcra-sdk"
dynamic = ["version"]
description = "SDK no oficial para las APIs del BCRA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.wheel]
packages = ["src/bcra_sdk"]

[dependency-groups]
dev = [
    "ipython>=9.15.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
