[project]
name = "bcra-sdk"
version = "0.1.0"
description = "SDK no oficial para las APIs del BCRA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
]

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.15.0",
    "pytest>=9.1.1",
]
